[project]
name = "chigrad"
version = "0.1.0"
description = "Correlated chi-squared fitting library for nucleon form factor extraction"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Christian Kindler" }]
dependencies = [
  "gvar",
  "numpy",
  "iminuit",
  "scipy"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
 
 
[tool.setuptools]
package-dir = {"" = "src"} 

[tool.setuptools.packages.find]
where = ["src"]
 
[project.urls]
Repository = "https://github.com/chriskindler/chigrad"
 
